version: '3.7'

services:

  postgres9:
    build: postgres9
    ports:
      - 5432
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       app

  postgres11:
    build: postgres11
    ports:
      - 5432
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       app

  bucardo:
    build: bucardo
    volumes:
      - ./conf/pg_service.conf:/etc/postgresql-common/pg_service.conf
    command:
      - bash
      - -c
      - |
        bucardo add db A dbservice=a
        bucardo add db B dbservice=b
        # Inserted data after next line will replicate.
        bucardo add sync migrate_db tables=all dbs=A,B
        pg_dump service=a --schema=public --section=data | psql -q service=b
        # bucardo start
        # replication start
        bash
        # tail -f /var/log/bucardo/log.bucardo
        # bucardo stop
        # pg_dump service=a --schema=public --section=post-data | psql -q service=b
        # bucardo remove sync migrate_db
        # bucardo remove db A B --force

  psql: &psql
    image: postgres:11
    volumes:
      - ./conf/pg_service.conf:/etc/postgresql-common/pg_service.conf
      - ./sql:/sql
    command: bash
  
  init:
    <<: *psql
    command:
      - bash
      - -c
      - |
        echo === a ===
        psql service=a -c 'CREATE EXTENSION plperl;'
        psql service=a < /sql/ddl.sql
        psql service=a < /sql/init.sql
        echo === b ===
        psql service=b -c 'CREATE EXTENSION plperl;'
        pg_dump service=a --schema=public --section=pre-data | psql -q service=b

  clean:
    <<: *psql
    command:
      - bash
      - -c
      - |
        echo === a ===
        psql service=a < /sql/clean.sql
        psql service=a -c 'DROP EXTENSION plperl;'
        echo === b ===
        psql service=b < /sql/clean.sql
        psql service=b -c 'DROP EXTENSION plperl;'
