version: '3.7'

services:

  postgres9:
    image: postgres:9.6-alpine
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app

  postgres11:
    image: postgres:11-alpine
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app

  bucardo:
    build: bucardo
